name: Go

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'  # فقط با تگ‌های شروع شده با v اجرا شود

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: darwin
            goarch: arm64
            platform: ios
            target: ios
          - goos: darwin
            goarch: amd64
            platform: ios-simulator
            target: ios

    runs-on: macos-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 1
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Show workflow information
        run: |
          export _NAME=$GOOS-$GOARCH
          if [ ! -z "${{ matrix.platform }}" ]; then
            export _NAME=$_NAME-${{ matrix.platform }}
          fi
          echo "GOOS: $GOOS, GOARCH: $GOARCH, PLATFORM: ${{ matrix.platform }}, RELEASE_NAME: $_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV
          echo "REF=${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS Framework
        run: |
          # ایجاد دایرکتوری‌های مورد نیاز
          mkdir -p build/ios
          
          # ساخت کتابخانه استاتیک و header
          go build -v -buildmode=c-archive -trimpath \
            -ldflags "-s -w -buildid= -X main.version=${{ github.ref }}" \
            -o build/ios/libwarp.a ./cmd/warp-plus
          
          # نمایش محتویات دایرکتوری برای debug
          echo "Contents of build/ios directory:"
          ls -la build/ios/
          
          # ایجاد ساختار فریمورک
          mkdir -p build/ios/Warp.framework/Headers
          
          # کپی فایل‌ها به مسیر درست
          cp build/ios/libwarp.a build/ios/Warp.framework/Warp
          
          # بررسی وجود فایل header
          if [ -f "build/ios/libwarp.h" ]; then
            cp build/ios/libwarp.h build/ios/Warp.framework/Headers/Warp.h
          else
            echo "Header file not found. Searching for it..."
            find build -name "*.h"
          fi
          
          # نمایش محتویات فریمورک
          echo "Contents of Warp.framework directory:"
          ls -la build/ios/Warp.framework/
          
          # ساخت فایل Info.plist برای فریمورک
          cat > build/ios/Warp.framework/Info.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleDevelopmentRegion</key>
              <string>en</string>
              <key>CFBundleExecutable</key>
              <string>Warp</string>
              <key>CFBundleIdentifier</key>
              <string>org.bepass.warp</string>
              <key>CFBundleInfoDictionaryVersion</key>
              <string>6.0</string>
              <key>CFBundleName</key>
              <string>Warp</string>
              <key>CFBundlePackageType</key>
              <string>FMWK</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>CFBundleVersion</key>
              <string>1</string>
              <key>MinimumOSVersion</key>
              <string>12.0</string>
          </dict>
          </plist>
          EOF

      - name: Create combined ZIP archive
        if: ${{ matrix.platform == 'ios' }}
        run: |
          # ایجاد دایرکتوری برای جمع‌آوری همه فریمورک‌ها
          mkdir -p combined/device
          mkdir -p combined/simulator
          
          # کپی فریمورک‌های مناسب به دایرکتوری‌های مربوطه
          if [[ "${{ matrix.platform }}" == "ios" ]]; then
            cp -R build/ios/Warp.framework combined/device/
          else
            cp -R build/ios/Warp.framework combined/simulator/
          fi
          
          # ایجاد فایل ZIP از همه فریمورک‌ها
          cd combined
          zip -r ../warp-ios-frameworks.zip .
          
          echo "Created combined ZIP archive"
          ls -la ../warp-ios-frameworks.zip

      - name: Upload iOS Framework
        uses: actions/upload-artifact@v4
        with:
          name: warp-plus_${{ env.ASSET_NAME }}_${{ env.REF }}
          path: build/ios/Warp.framework

      - name: Upload combined ZIP
        if: ${{ matrix.platform == 'ios' }}
        uses: actions/upload-artifact@v4
        with:
          name: warp-ios-frameworks
          path: warp-ios-frameworks.zip

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Display structure of downloaded files
        run: ls -R artifacts
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/warp-ios-frameworks/warp-ios-frameworks.zip
          draft: false
          prerelease: false
          generate_release_notes: true
